export type MainStackParamList = {
  Home: undefined;
  Support: undefined;
  AccountDetails: undefined;
  Payments: undefined;
  PaymentContacts: undefined;
  PaymentLimits: undefined;
  CardManagement: undefined;
  Settings: undefined;
  FingerprintLogin: undefined;
  ResetPassword: undefined;
  AutoLogoff: undefined;
  ResetApp: undefined;
  NotificationSettings: undefined;
  PaperFreePreferences: undefined;
  StatementFrequency: undefined;
  AccessibilityOptions: undefined;
  OpenBankingAccounts: undefined;
  AppDetails: undefined;
  MarketingChoices: undefined;
  DataConsent: undefined;
  OpenBankingServices: undefined;
  LegalInformation: undefined;
  RegularPayments: undefined;
  Statements: undefined;
  Inbox: undefined;
};